### ISSUE TITLE
I need some help

### ISSUE THREAD

**Issue by GemedeHD** [lifehackerhansol/flashcard-archive#1]
I found this website on reddit so maybe you can solve my issue. My problem is that I have two old flashcarts which servers shutted down. I didn't find any firmware or anything that could support the v.1.4.5E of my dsi. Any suggestion? I send you a picture where I show them. (Maybe the second one is harder to find beacuse it is older)

![WhatsApp Image 2021-06-16 at 17 47 20](https://user-images.githubusercontent.com/86012024/122252553-baa52480-cecb-11eb-9b45-1579f354ee6d.jpeg)

**Comment by lifehackerhansol** [comment]
I have uploaded the iTouchDS kernel to its respective folder. See commit above.

While I can upload the kernel for the R4i 3DS, because it is better to run YSMenu on those, you will need YSMenu (which I am not allowed to share here). I'll post instructions on how for that cart in its respective folder, which will be within the YSMenu folder. Stay tuned.

**Comment by GemedeHD** [comment]
Thank you so much for your time, i'll try the iTouch one tomorrow and stay tuned for the R4i one :)

**Comment by GemedeHD** [comment]
I finally tried it tonight, first the iTouch seems not to work anymore so I tried with the r4i-gold.eu, I did every step but the last one was so confusing because I didn't find any YSMenu.nds so I don't know what to do and neither did I understand the readme.txt from the DEMON bootloader folder. Sorry for the inconveniences and for my english level :(
